import Config

# Configure your database
config :trading_options_sim, TradingOptionsSim.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "trading_options_sim_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :trading_options_sim, TradingOptionsSimWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  # Port 4008 — next free slot after the sibling apps' 4000-4007 range
  # (trading_hub 4000, trading_risk 4001, trading_dashboard 4002,
  # trading_system 4004 UI / 4005 API, trading_signal 4006, trading_live
  # 4007). See OPTIONS_SIM_ARCHITECTURE_PLAN.md §9.
  http: [ip: {127, 0, 0, 1}, port: String.to_integer(System.get_env("PORT") || "4008")],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "jXm6JDhrE46p8+c+mHiS5155a/KSqAy4kEy5FM/yV7N+oHG7NNCfbmnr2GSCzKsi",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:trading_options_sim, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:trading_options_sim, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :trading_options_sim, dev_routes: true

# trading_hub node to connect to via IbPortfolio.HubClient (see
# OPTIONS_SIM_ARCHITECTURE_PLAN.md §4c) — same convention trading_live/
# trading_risk already use.
config :trading_options_sim, :hub_node, :"trading_hub@Scotts-Mac-mini.local"

# trading_signal node to connect to via SignalConnection — same
# convention as :hub_node above, matching trading_live's identical
# :signal_node config.
config :trading_options_sim, :signal_node, :"trading_signal@Scotts-Mac-mini.local"

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
